In [9]:
import pandas as pd

#lit les clients dtype=str garde le code psotal en texte

customers = pd.read_csv('../data/raw/olist_customers_dataset.csv', dtype={'customer_zip_code_prefix': str})

# lit les commandes

orders = pd.read_csv('../data/raw/olist_orders_dataset.csv')

print(customers.shape, orders.shape)
customers.head()

(99441, 5) (99441, 8)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,09790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,01151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,08775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [10]:
#convertis la date lue comme du texte en vraie date

orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])

In [11]:
# par customer_id, on relie commande à client

cmd = orders.merge(customers, on='customer_id')
print(len(cmd))

99441

In [12]:
dim_client = (dim_client.reset_index(drop=True)
              .rename(columns={'customer_city': 'ville', 'customer_zip_code_prefix': 'code_postal_prefixe'})
              [['customer_unique_id', 'ville', 'code_postal_prefixe']])

In [13]:
#garde une numeration propre et controle dim_client

assert list(dim_client.columns) == ['customer_unique_id', 'ville', 'code_postal_prefixe']
assert len(dim_client) == 96096
assert dim_client['customer_unique_id'].is_unique
assert dim_client['code_postal_prefixe'].str.len().eq(5).all()
assert dim_client.isna().sum().sum() == 0
print("Contrôles DimClient OK")
dim_client.head()

Contrôles DimClient OK

                 customer_unique_id                 ville code_postal_prefixe
0  b7d76e111c89f7ebf14761390f0f7d17             boa vista               69309
1  4854e9b3feff728c13ee5fc7d1547e92           passo fundo               99025
2  009b0127b727ab0ba422f6d9604487c7   sao jose dos campos               12244
3  830d5b7aaa3b6f1e9ad63703bec97d23  sao joaquim da barra               14600
4  0eb1ee9dba87f5b36b4613a65074337c             sao paulo               02975